# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Check Pull Request Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  semantic-message:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@24e6f016c1e110f5353026c0b6129a4118b9146c # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
