# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '24.1'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm i
      - name: Lint with prettier
        run: pnpm run lint
      - name: Install playwright browser
        run: pnpm exec playwright install --with-deps chromium
      - name: Build website
        run: pnpm run build
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        if: github.ref == 'refs/heads/main'
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::855808870739:role/github-actions-jetski.sh
      - name: Deploy short lived content
        if: github.ref == 'refs/heads/main'
        run: >-
          aws s3 sync dist s3://jetski.sh/
          --cache-control "max-age=60, public"
          --acl=public-read
      - name: Deploy long lived content
        if: github.ref == 'refs/heads/main'
        run: >-
          aws s3 sync dist/_astro s3://jetski.sh/_astro
          --cache-control "max-age=604800, public"
          --acl=public-read
      - name: Invalidate cache
        if: github.ref == 'refs/heads/main'
        run: >-
          aws cloudfront create-invalidation
          --distribution-id E1OJSRCMNHM1NE
          --invalidation-batch "Paths={Quantity='1' ,Items=['/*']},CallerReference=WEBSITE_$GITHUB_RUN_ID"
