# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: 10
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '24.10'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm i
      - name: Lint with prettier
        run: pnpm run lint
      - name: Install playwright browser
        run: pnpm exec playwright install --only-shell
      - name: Build website
        run: pnpm run build
      - uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5
        if: github.ref == 'refs/heads/main'
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::855808870739:role/github-actions-jetski.sh
      - name: Deploy short lived content
        if: github.ref == 'refs/heads/main'
        run: >-
          aws s3 sync dist s3://hyprmcp.com/
          --cache-control "max-age=60, public"
          --acl=public-read
      - name: Deploy long lived content
        if: github.ref == 'refs/heads/main'
        run: >-
          aws s3 sync dist/_astro s3://hyprmcp.com/_astro
          --cache-control "max-age=604800, public"
          --acl=public-read
      - name: Invalidate cache
        if: github.ref == 'refs/heads/main'
        run: >-
          aws cloudfront create-invalidation
          --distribution-id EH7B7Z7YWWXSF
          --invalidation-batch "Paths={Quantity='1' ,Items=['/*']},CallerReference=WEBSITE_$GITHUB_RUN_ID"
